CREATE TABLE MANAGER(
id INTEGER PRIMARY KEY,
name VARCHAR(25),
age INTEGER , 
birthdate DATE DEFAULT sysdate,
address VARCHAR(225)
);



ALTER TABLE MANAGER DROP COLUMN address ;

ALTER TABLE MANAGER  ADD (city_address VARCHAR(225),street VARCHAR(20)); 


ALTER TABLE MANAGER RENAME COLUMN name TO full_name;

ALTER TABLE MANAGER  READ ONLY;
CREATE  TABLE OWNER AS SELECT * FROM MANAGER ;
ALTER TABLE OWNER  DROP (age,city_address,street);
ALTER TABLE MANAGER RENAME TO Master ;

DROP TABLE Master ;

