CREATE TABLE Employees_COPY
( EmployeeID INTEGER PRIMARY KEY, FirstName VARCHAR2(222), LastName VARCHAR2(222), Department VARCHAR2(22), Salary NUMBER );
----------------------------------------------------------------

INSERT  INTO 
EMPLOYEES_COPY(EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENT,SALARY) VALUES(101,'John1','Doe1','HR' ,20000);
INSERT  INTO 
EMPLOYEES_COPY(EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENT,SALARY) VALUES (102,'John2','Doe2','IT',50000);
INSERT  INTO 
EMPLOYEES_COPY(EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENT,SALARY)VALUES (103,'John3','Doe3','CS'     ,       40000);
INSERT  INTO 
EMPLOYEES_COPY(EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENT,SALARY) VALUES (104           , 'John4'    ,  'Doe4'   ,  'IT'      ,      10000);	
INSERT  INTO 
EMPLOYEES_COPY(EMPLOYEEID,FIRSTNAME,LASTNAME,DEPARTMENT,SALARY) VALUES (105          ,  'John5'    ,  'Doe5'  ,   'ZX'       ,     30000);

UPDATE EMPLOYEES_COPY SET SALARY =60000 WHERE EMPLOYEEID =101;

DELETE FROM EMPLOYEES_COPY WHERE EMPLOYEEID = 101;

FLASHBACK TABLE EMPLOYEES_COPY TO BEFORE DROP ;
SELECT EMPLOYEEID,DEPARTMENT,SALARY ,FIRSTNAME||','||LASTNAME AS FN FROM EMPLOYEES_COPY ; 